[project]
name = 'All contracts repository'
description = ''
authors = []
telemetry = false
cache_dir = '.\.cache'
requirements = []
[contracts.achievement-badge]
path = 'contracts/achievement-badge.clar'
clarity_version = 3
epoch = 'latest'

[contracts.auth-registry]
path = 'contracts/auth-registry.clar'
clarity_version = 3
epoch = 'latest'

[contracts.billboard]
path = 'contracts/billboard.clar'
clarity_version = 3
epoch = 'latest'

[contracts.config-store]
path = 'contracts/config-store.clar'
clarity_version = 3
epoch = 'latest'

[contracts.data-registry]
path = 'contracts/data-registry.clar'
clarity_version = 3
epoch = 'latest'

[contracts.event-logger]
path = 'contracts/event-logger.clar'
clarity_version = 3
epoch = 'latest'

[contracts.flash-loan-record]
path = 'contracts/flash-loan-record.clar'
clarity_version = 3
epoch = 'latest'

[contracts.fungible-token]
path = 'contracts/fungible-token.clar'
clarity_version = 3
epoch = 'latest'

[contracts.hello-world]
path = 'contracts/hello-world.clar'
clarity_version = 3
epoch = 'latest'

[contracts.kv-store]
path = 'contracts/kv-store.clar'
clarity_version = 3
epoch = 'latest'

[contracts.liquidity-pool]
path = 'contracts/liquidity-pool.clar'
clarity_version = 3
epoch = 'latest'

[contracts.math-utils]
path = 'contracts/math-utils.clar'
clarity_version = 3
epoch = 'latest'

[contracts.message-board]
path = 'contracts/message-board.clar'
clarity_version = 3
epoch = 'latest'

[contracts.multisig-helper]
path = 'contracts/multisig-helper.clar'
clarity_version = 3
epoch = 'latest'

[contracts.name-service]
path = 'contracts/name-service.clar'
clarity_version = 3
epoch = 'latest'

[contracts.non-fungible-token]
path = 'contracts/non-fungible-token.clar'
clarity_version = 3
epoch = 'latest'

[contracts.permission-manager]
path = 'contracts/permission-manager.clar'
clarity_version = 3
epoch = 'latest'

[contracts.proposal-submission]
path = 'contracts/proposal-submission.clar'
clarity_version = 3
epoch = 'latest'

[contracts.registry-controller]
path = 'contracts/registry-controller.clar'
clarity_version = 3
epoch = 'latest'

[contracts.reputation-system]
path = 'contracts/reputation-system.clar'
clarity_version = 3
epoch = 'latest'

[contracts.simple-counter]
path = 'contracts/simple-counter.clar'
clarity_version = 3
epoch = 'latest'

[contracts.sip-009-trait]
path = 'contracts/sip-009-trait.clar'
clarity_version = 3
epoch = 'latest'

[contracts.sip-010-trait]
path = 'contracts/sip-010-trait.clar'
clarity_version = 3
epoch = 'latest'

[contracts.stacking-logger]
path = 'contracts/stacking-logger.clar'
clarity_version = 3
epoch = 'latest'

[contracts.status-tracker]
path = 'contracts/status-tracker.clar'
clarity_version = 3
epoch = 'latest'

[contracts.string-utils]
path = 'contracts/string-utils.clar'
clarity_version = 3
epoch = 'latest'

[contracts.timestamp-logger]
path = 'contracts/timestamp-logger.clar'
clarity_version = 3
epoch = 'latest'

[contracts.tip-jar]
path = 'contracts/tip-jar.clar'
clarity_version = 3
epoch = 'latest'

[contracts.user-profile]
path = 'contracts/user-profile.clar'
clarity_version = 3
epoch = 'latest'

[contracts.version-control]
path = 'contracts/version-control.clar'
clarity_version = 3
epoch = 'latest'

[contracts.voting-poll]
path = 'contracts/voting-poll.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
