[project]
name = 'All contracts repository'
description = ''
authors = []
telemetry = false
cache_dir = '.\.cache'
requirements = []
[contracts.achievement-badge]
path = 'contracts/achievement-badge.clar'
clarity_version = 3
epoch = 'latest'

[contracts.auth-registry]
path = 'contracts/auth-registry.clar'
clarity_version = 3
epoch = 'latest'

[contracts.billboard]
path = 'contracts/billboard.clar'
clarity_version = 3
epoch = 'latest'

[contracts.config-store]
path = 'contracts/config-store.clar'
clarity_version = 3
epoch = 'latest'

[contracts.data-registry]
path = 'contracts/data-registry.clar'
clarity_version = 3
epoch = 'latest'

[contracts.event-logger]
path = 'contracts/event-logger.clar'
clarity_version = 3
epoch = 'latest'

[contracts.flash-loan-record]
path = 'contracts/flash-loan-record.clar'
clarity_version = 3
epoch = 'latest'

[contracts.fungible-token]
path = 'contracts/fungible-token.clar'
clarity_version = 3
epoch = 'latest'

[contracts.hello-world]
path = 'contracts/hello-world.clar'
clarity_version = 3
epoch = 'latest'

[contracts.kv-store]
path = 'contracts/kv-store.clar'
clarity_version = 3
epoch = 'latest'

[contracts.liquidity-pool]
path = 'contracts/liquidity-pool.clar'
clarity_version = 3
epoch = 'latest'

[contracts.math-utils]
path = 'contracts/math-utils.clar'
clarity_version = 3
epoch = 'latest'

[contracts.message-board]
path = 'contracts/message-board.clar'
clarity_version = 3
epoch = 'latest'

[contracts.multisig-helper]
path = 'contracts/multisig-helper.clar'
clarity_version = 3
epoch = 'latest'

[contracts.name-service]
path = 'contracts/name-service.clar'
clarity_version = 3
epoch = 'latest'

[contracts.non-fungible-token]
path = 'contracts/non-fungible-token.clar'
clarity_version = 3
epoch = 'latest'

[contracts.permission-manager]
path = 'contracts/permission-manager.clar'
clarity_version = 3
epoch = 'latest'

[contracts.proposal-submission]
path = 'contracts/proposal-submission.clar'
clarity_version = 3
epoch = 'latest'

[contracts.registry-controller]
path = 'contracts/registry-controller.clar'
clarity_version = 3
epoch = 'latest'

[contracts.reputation-system]
path = 'contracts/reputation-system.clar'
clarity_version = 3
epoch = 'latest'

[contracts.simple-counter]
path = 'contracts/simple-counter.clar'
clarity_version = 3
epoch = 'latest'

[contracts.sip-009-trait]
path = 'contracts/sip-009-trait.clar'
clarity_version = 3
epoch = 'latest'

[contracts.sip-010-trait]
path = 'contracts/sip-010-trait.clar'
clarity_version = 3
epoch = 'latest'

[contracts.stacking-logger]
path = 'contracts/stacking-logger.clar'
clarity_version = 3
epoch = 'latest'

[contracts.status-tracker]
path = 'contracts/status-tracker.clar'
clarity_version = 3
epoch = 'latest'

[contracts.string-utils]
path = 'contracts/string-utils.clar'
clarity_version = 3
epoch = 'latest'

[contracts.timestamp-logger]
path = 'contracts/timestamp-logger.clar'
clarity_version = 3
epoch = 'latest'

[contracts.tip-jar]
path = 'contracts/tip-jar.clar'
clarity_version = 3
epoch = 'latest'

[contracts.user-profile]
path = 'contracts/user-profile.clar'
clarity_version = 3
epoch = 'latest'

[contracts.version-control]
path = 'contracts/version-control.clar'
clarity_version = 3
epoch = 'latest'

[contracts.voting-poll]
path = 'contracts/voting-poll.clar'
clarity_version = 3
epoch = 'latest'

[contracts.achievement-badge-v2]
path = 'contracts/achievement-badge-v2.clar'
clarity_version = 4
epoch = '3.3'

[contracts.auth-registry-v2]
path = 'contracts/auth-registry-v2.clar'
clarity_version = 4
epoch = '3.3'

[contracts.backup-wallet-v2]
path = 'contracts/backup-wallet-v2.clar'
clarity_version = 4
epoch = '3.3'

[contracts.billboard-v2]
path = 'contracts/billboard-v2.clar'
clarity_version = 4
epoch = '3.3'

[contracts.config-store-v2]
path = 'contracts/config-store-v2.clar'
clarity_version = 4
epoch = '3.3'

[contracts.data-registry-v2]
path = 'contracts/data-registry-v2.clar'
clarity_version = 4
epoch = '3.3'

[contracts.event-logger-v2]
path = 'contracts/event-logger-v2.clar'
clarity_version = 4
epoch = '3.3'

[contracts.flash-loan-record-v2]
path = 'contracts/flash-loan-record-v2.clar'
clarity_version = 4
epoch = '3.3'

[contracts.fungible-token-v2]
path = 'contracts/fungible-token-v2.clar'
clarity_version = 4
epoch = '3.3'

[contracts.hello-world-v2]
path = 'contracts/hello-world-v2.clar'
clarity_version = 4
epoch = '3.3'

[contracts.kv-store-v2]
path = 'contracts/kv-store-v2.clar'
clarity_version = 4
epoch = '3.3'

[contracts.liquidity-pool-v2]
path = 'contracts/liquidity-pool-v2.clar'
clarity_version = 4
epoch = '3.3'

[contracts.math-utils-v2]
path = 'contracts/math-utils-v2.clar'
clarity_version = 4
epoch = '3.3'

[contracts.message-board-v2]
path = 'contracts/message-board-v2.clar'
clarity_version = 4
epoch = '3.3'

[contracts.multisig-helper-v2]
path = 'contracts/multisig-helper-v2.clar'
clarity_version = 4
epoch = '3.3'

[contracts.name-service-v2]
path = 'contracts/name-service-v2.clar'
clarity_version = 4
epoch = '3.3'

[contracts.non-fungible-token-v2]
path = 'contracts/non-fungible-token-v2.clar'
clarity_version = 4
epoch = '3.3'

[contracts.permission-manager-v2]
path = 'contracts/permission-manager-v2.clar'
clarity_version = 4
epoch = '3.3'

[contracts.proposal-submission-v2]
path = 'contracts/proposal-submission-v2.clar'
clarity_version = 4
epoch = '3.3'

[contracts.registry-controller-v2]
path = 'contracts/registry-controller-v2.clar'
clarity_version = 4
epoch = '3.3'

[contracts.reputation-system-v2]
path = 'contracts/reputation-system-v2.clar'
clarity_version = 4
epoch = '3.3'

[contracts.simple-counter-v2]
path = 'contracts/simple-counter-v2.clar'
clarity_version = 4
epoch = '3.3'

[contracts.sip-009-trait-v2]
path = 'contracts/sip-009-trait-v2.clar'
clarity_version = 4
epoch = '3.3'

[contracts.sip-010-trait-v2]
path = 'contracts/sip-010-trait-v2.clar'
clarity_version = 4
epoch = '3.3'

[contracts.stacking-logger-v2]
path = 'contracts/stacking-logger-v2.clar'
clarity_version = 4
epoch = '3.3'

[contracts.status-tracker-v2]
path = 'contracts/status-tracker-v2.clar'
clarity_version = 4
epoch = '3.3'

[contracts.string-utils-v2]
path = 'contracts/string-utils-v2.clar'
clarity_version = 4
epoch = '3.3'

[contracts.timestamp-logger-v2]
path = 'contracts/timestamp-logger-v2.clar'
clarity_version = 4
epoch = '3.3'

[contracts.tip-jar-v2]
path = 'contracts/tip-jar-v2.clar'
clarity_version = 4
epoch = '3.3'

[contracts.user-profile-v2]
path = 'contracts/user-profile-v2.clar'
clarity_version = 4
epoch = '3.3'

[contracts.version-control-v2]
path = 'contracts/version-control-v2.clar'
clarity_version = 4
epoch = '3.3'

[contracts.voting-poll-v2]
path = 'contracts/voting-poll-v2.clar'
clarity_version = 4
epoch = '3.3'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
